### ISSUE TITLE
How to generate input files for this workflow directly from Seurat object

### ISSUE THREAD

**Issue by bharati-mehani** [jdime/scRNAseq_cell_cluster_labeling#4]
Hi Javier, 
Thank you for this benchmarking tool. I have already identified cell clusters in my dataset using cell ranger and Seurat and now willing to use your workflow. This could be a naive question, but I am really curious to ask how should I proceed to generate the needed input files for the main wrapper script directly from my Seurat object. 

Is there any manual (which may be I am missing) that have already listed the order of commands or scripts to follow in-order to infer labels for my cell-clusters

I'll really appreciate your help and suggestions.
Thanks.

**Comment by bharati-mehani** [comment]
Hi @jdime , Can you or somebody help and suggest something about the above said problem?

**Comment by jdime** [comment]
Hello,
You'll need two input files:
a) Average gene expression with genes (rows) and cell clusters (columns). In Seurat v3 you can use function AverageExpression() to get that. We also provide this one-line-command script to get that from your read counts and defined clusters.
`https://github.com/jdime/scRNAseq_cell_cluster_labeling/blob/master/bin/r_programs/obtains_average_gene_expression_per_cluster.R`

b) Cell type signatures. I'm not sure which type of cells you are working with, but this needs to be lists of genes (markers) characterizing each of the cell types you are interested to identify. In our F1000 Research paper (https://f1000research.com/articles/8-296) we provided examples for some tissues from human and mouse. If the type of cells/tissues that you are studying match those cells feel free to use them (follow the Zenodo link in that publication), otherwise you'll need to compile them from literature and/or gene marker databases. What cell type, tissues and species you are working with?

In addition, if you want to benchmark methods, you'll need gold standards. These also need to be compiled from literature and are not easy to find. Let's first talk about the two inputs I mention above.

J.

**Comment by bharati-mehani** [comment]
Hi @jdime 
Thank you for your kind reply. I am handling scRNA Seq from glioma samples, Can you please elaborate how can I make gold standard cluster labels, I already have cluster label predictions from singleR, can I use that as a way out?
Really looking forward to your suggestions.
Thanks

**Comment by jdime** [comment]
You need to know Cluster to Cell type annotations that you trust as ground truth. In our F1000 Research publication we obtained gold standards from the papers (usually supplementary info) from the original scRNA-seq dataset publications.
However, if you think your inferences from singleR are good enough to be used as ground truth, yes, you can use them.
Note, you need this only if you are aiming to benchmark labeling methods. If you simply want to make predictions using those methods, then you don't need gold standards.
